algoritmo "semnome"
// Função :
// Autor :
// Data : 21/02/2019
// Seção de Declarações 
var
largura,comprimento,media,btus,nmp:real
inicio
escreval ("qual o comprimento da sala")
leia(comprimento)
escreval("qual a largura da sala")
leia(largura)
escreval("qual a quantidade média de pessoas que frequentam a sala")
leia (nmp)
Btus<-largura*comprimento*600+nmp
escreval (btus)

// Seção de Comandos 
fimalgoritmo
