algoritmo "semnome"
// Função :
// Autor :
// Data : 31/03/2019
// Seção de Declarações 
var
 cont,num,qa,qb:inteiro
inicio
para cont de 1 ate 2 passo 1 faca
escreval ("digite um numero")
leia (num)
se (num mod 2=8) entao
qa<-qa+1
senao
qb<-qb+1
fimse
fimpara
escreval (" toda vez que o numero for  igual 8, entao:",qa)
escreval ("toda vez que o numero não for igual  8, entao:",qb)

// Seção de Comandos 
fimalgoritmo
