algoritmo "Atividade4"
// Função :
// Autor :
// Data : 30/03/2019
// Seção de Declarações 
var
idade,nascimento,atual,x:inteiro
inicio
//entrada de dados
escreval ("digite a idade")
leia (idade)
escreval ("digite o ano de nascimento")
leia (nascimento)
escreval ("digite o ano atual")
leia (atual)
//processamento
x<-(atual-nascimento)
se (idade=x) entao
escreval ("idade confere")
senao
escreval("idade não confere")
fimse
// Seção de Comandos 
fimalgoritmo
