algoritmo "semnome"
// Função :
// Autor :
// Data : 07/03/2019
// Seção de Declarações 
var
A,B,C,D:caracter

inicio
escreval ("informe o valor de B")
leia(B)
escreval ("informe o valor de C")
leia (C)
escreval ("informe o valor de A")
leia (A)
escreval ("informe o valor de D")
leia (D)
se (B>C) e (D>A) e  (C+D>A+B) e (c>0) (d>0) e (a mod 2-0) entao
 escreval ("valores aceitos")
 senao
 escreval ("valores não aceitos")
 fimse
// Seção de Comandos 
fimalgoritmo
