algoritmo "semnome"
// Função :
// Autor :
// Data : 07/03/2019
// Seção de Declarações
var
soma,multi,quadrado,numero,valor,valor1:real
inicio
escreval ("informe um valor")
leia (valor)
escreval ("informe um segundo valor")
leia (valor1)
se (valor>-100)entao
   multi<-numero*3
   senao
se (valor<100)entao
   escreval (" o numero quadrado é:", numero*numero)



// Seção de Comandos
fimalgoritmo
fimse
fimalgoritmo
fimse
fimalgoritmo
